### ISSUE TITLE
Не запускается rhvoice в контейнере docker

### ISSUE THREAD

**Issue by ankxyz** [mnrozhkov/candybot_vr#23]
установка rhvoice (детали - https://launchpad.net/~linvinus/+archive/ubuntu/rhvoice):
sudo add-apt-repository ppa:linvinus/rhvoice
sudo apt-get update

установка как клиент-сервер:
sudo apt-get install rhvoice rhvoice-russian rhvoice-english

установка как модуль speech-dispatcher:
sudo apt-get install speech-dispatcher-rhvoice rhvoice-russian rhvoice-english

=== Использование ===
1) Если вы установили пакет rhvoice то нужно выполнить команду
echo "Проверка синтезатора речи" | RHVoice-client -s Anna+CLB | aplay

2) Если вы установили пакет speech-dispatcher-rhvoice то нужно выполнить команду
echo "Проверка синтезатора речи" | spd-say -o rhvoice -l ru -e -t female1

Проблема: не работает **в docker контейнере** 
![2016-10-26 10-37-59](https://cloud.githubusercontent.com/assets/21148145/19828884/f51dd918-9e15-11e6-87f6-14ba2d5e59a9.png)

В реальной Ubuntu приложение spd-say использует сокет по адресу /run/user/1000/speech-dispatcher/speechd.sock , который (вместе с каталогом) создается в момент запуска spd-say.
Если передать этот сокет в контейнер:
sudo docker run -ti -v run/user/1000/speech-dispatcher/speechd.sock:/root/.cache/speech-dispatcher/speechd.sock full_rpo ,
то spd-say работает.
Предположительно проблема в работе сети внутри контейнера

**Comment by ilyar** [comment]
@MeisterUrian получилось запустить?

**Comment by ankxyz** [comment]
@ilyar К сожалению, так и не получилось. Если передавать unix-сокет speech-dispatcher-а внутрь контейнера, тогда всё работает.
Получается, что внутри контейнера speech-dispatcher не может создать сокет.
