### ISSUE TITLE
Написать класс MessageHandler

### ISSUE THREAD

**Issue by ankxyz** [mnrozhkov/candybot_vr#28]
- [ ] 
  классMessageHandler предназначен для управления объектами класса Subscriber и callback-функциями
  методы:
  create_new_callback - создание callback-функции для передачи в дальнейшем в конструктор объекта класса Subscriber
  create_new_subscriber - создание нового объекта класса Subscriber
  handle - запуск цикла приема сообщений

Преимущества класса:
1. уменьшение количества кода
2. возможность создания и модификации "на лету" callback-функций и объектов класса Subscriber

**Comment by mnrozhkov** [comment]
это еще актуально ?

**Comment by ankxyz** [comment]
Оно тут все оставшееся неактуально, т.к. произошли значительные изменения
