### ISSUE TITLE
Возможные действия робота в ответ на эмоции человека

### ISSUE THREAD

**Issue by ankxyz** [mnrozhkov/candybot_vr#32]
улыбка -> приветствие

просьба о фото -> подготовка робота к фото + улыбка -> сделать фото (например, человек попросил о фото, робот приготовился и сказал "улыбочку!", как только есть улыбка, делается фото

степень "запоминаемости" человека довольно высокая -> робот говорит об этом | предлагает сделать фото | выдает конфетку/другой приз

человек грустный -> только приветствие и ожидании общения| приветствие + вопрос типа ("как дела" | "почему грустишь") | предложение рассказать анекдот | рассказ анекдота (как бы случайно, "слушай анекдот: ....")

человек похож на звезду [к сожалению, звезды только заграничные] -> сообщить об этом человеку | предложить сделать фото

**Comment by mnrozhkov** [comment]
Перенесено в Candybot_ТЗ_2.Software Specifications_v1
