### ISSUE TITLE
Перенести face_tracker в папку vision 

### ISSUE THREAD

**Issue by mnrozhkov** [mnrozhkov/candybot_vr#36]
Если нужны служебные функции  для работы с opencv, предлагаю создать в vision папку 'utils'

**Comment by ankxyz** [comment]
Я подумал, что имеет смысл подчеркнуть, с помощью какой технологии (OpenCV, Algoritmia) реализуется конкретный функционал: opencv.face_tracker.py -> значит точно OpenCV
