### ISSUE TITLE
Избавиться от 'main' функции там, где она не нужна (на примере vision_camera_capture.py)

### ISSUE THREAD

**Issue by mnrozhkov** [mnrozhkov/candybot_vr#39]
вот этот фрагмет кода можно переписать так: 

```
def main():
    '''Main function
    '''
    try:
       ...
    except Exception as e:
       ...


if __name__ == '__main__':
    main()
```

предлагаю переписать так: 

```
if __name__ == '__main__':
    try:
       ...
    except Exception as e:
       ...
```

**Comment by ankxyz** [comment]
можно так, но принято вообще-то выделять main(), а в if __name__ == '__main__' выносить парсинг аргументов комадной строки, если таковые есть, и передавать их в функцию main()
