### ISSUE TITLE
Add tests for motion_eyes_controller

### ISSUE THREAD

**Issue by mnrozhkov** [mnrozhkov/candybot_vr#61]

**Comment by ankxyz** [comment]
![image](https://cloud.githubusercontent.com/assets/21148145/26637816/77729c4e-465b-11e7-9ca4-6b8fad2ec92e.png)

**Comment by ankxyz** [comment]
При одних и тех же входных данных (значении угла и расстоянию от края в процентах) глаза "скачут": возвращаются разные значения состояния (координат) глаз

![image](https://cloud.githubusercontent.com/assets/21148145/26753762/c4500bd8-48a8-11e7-8add-a7f0eb12a884.png)
