### ISSUE TITLE
fix hardware bug in motion/body 

### ISSUE THREAD

**Issue by ankxyz** [mnrozhkov/candybot_vr#76]
![image](https://cloud.githubusercontent.com/assets/21148145/25586219/64072380-2ed9-11e7-8165-4ccaae5e68e9.png)

**Comment by ankxyz** [comment]
roscore

в другом терминале, в папке cw:
source devel/setup.bash

запуск motion-контроллера
rosrun coffebot motion_body_controller.py

запуск соответствующего теста (в новом терминале, при запущенном motion-контроллере)
rosrun coffebot test_motion_body_controller.py

**Comment by mnrozhkov** [comment]
Проблема в конструкторе Servo() !!! 

При подключении 1 PCA9685 не нужно указывать адрес в self.pca9685 = Adafruit_PCA9685.PCA9685(address)  
Более того, при создании объекта PCA9685() умолчанию используется адрес 0x40 

В случае подключения нескольких модулей PCA9685 пример можно найти здесь: https://learn.adafruit.com/16-channel-pwm-servo-driver/chaining-drivers   

TODO:
1. Исправить конструктор Servo() 
- убрать 'address' в создании объекта pca9685
- переименовать 'address' в 'channel'
2. В конструкторах классов Body  переименовать параметр _d_SERVO_ADDRESS в _d_SERVO_CHANNEL
3. То же сделать для  Eyebrows, Head
4. Внести изменения в тесты
